### ISSUE TITLE
I can't call HiGHS from PuLP anymore

### ISSUE THREAD

**Issue by yahyamert** [ERGO-Code/HiGHS#1633]
Hello,

I was using HiGHS for our senior project. It used to work 2 months ago but I had to delete and re-install Anaconda, PuLP, and HiGHS. 

Now I can't run the same code I used to run. I have tried to install HiGHS on different computers but every time I got the same error.

The steps I used to install PuLP and HiGHS are:

PuLP: 

python -m pip install pulp
Version: Successfully installed pulp-2.8.0

HiGHS:

pip install highspy
Version: Successfully installed highspy-1.5.3

The error I get when I try to run HiGHS is:

  File "c:\users\mert.akyildiz-ug\desktop\uiandcode.py", line 203, in run_optimization
    result = model.solve(solver)

  File "C:\Users\mert.akyildiz-ug\AppData\Roaming\Python\Python39\site-packages\pulp\pulp.py", line 1883, in solve
    status = solver.actualSolve(self, **kwargs)

  File "C:\Users\mert.akyildiz-ug\AppData\Roaming\Python\Python39\site-packages\pulp\apis\highs_api.py", line 481, in actualSolve
    self.createAndConfigureSolver(lp)

  File "C:\Users\mert.akyildiz-ug\AppData\Roaming\Python\Python39\site-packages\pulp\apis\highs_api.py", line 329, in createAndConfigureSolver
    lp.solverModel.setLogCallback(*callbackTuple)

AttributeError: 'Highs' object has no attribute 'setLogCallback'

I use HiGHS Api in PuLP: result = model.solve(HiGHS())

**Comment by yahyamert** [comment]
Quick addition:

We have commented out setLogCallback from highsapi.py and it worked. We can get solution now. I don't really know the reason why it has occurred. I would still like to discuss on the topic and find the root cause.

        def createAndConfigureSolver(self, lp):
            lp.solverModel = highspy.Highs()

            if self.msg or self.callbackTuple:
                callbackTuple = self.callbackTuple or (
                    HiGHS.DEFAULT_CALLBACK,
                    HiGHS.DEFAULT_CALLBACK_VALUE,
                )
                **#lp.solverModel.setLogCallback(*callbackTuple)**

            if self.gapRel is not None:
                lp.solverModel.setOptionValue("mip_rel_gap", self.gapRel)

            if self.gapAbs is not None:
                lp.solverModel.setOptionValue("mip_abs_gap", self.gapAbs)

            if self.threads is not None:
                lp.solverModel.setOptionValue("threads", self.threads)

            if self.timeLimit is not None:
                lp.solverModel.setOptionValue("time_limit", float(self.timeLimit))

            # set remaining parameter values
            for key, value in self.optionsDict.items():
                lp.solverModel.setOptionValue(key, value)

I have bolded the part we have modified. It looks like it works now.

**Comment by yahyamert** [comment]
I mistakently closed the issue so I open again sorry for creating a mess

**Comment by yahyamert** [comment]
I mistakently closed the issue so I open again sorry for creating a mess

**Comment by yahyamert** [comment]
Quick addition:

We have commented out setLogCallback from highsapi.py and it worked. We can get solution now. I don't really know the reason why it has occurred. I would still like to discuss on the topic and find the root cause.

    def createAndConfigureSolver(self, lp):
        lp.solverModel = highspy.Highs()

        if self.msg or self.callbackTuple:
            callbackTuple = self.callbackTuple or (
                HiGHS.DEFAULT_CALLBACK,
                HiGHS.DEFAULT_CALLBACK_VALUE,
            )
            **#lp.solverModel.setLogCallback(*callbackTuple)**

        if self.gapRel is not None:
            lp.solverModel.setOptionValue("mip_rel_gap", self.gapRel)

        if self.gapAbs is not None:
            lp.solverModel.setOptionValue("mip_abs_gap", self.gapAbs)

        if self.threads is not None:
            lp.solverModel.setOptionValue("threads", self.threads)

        if self.timeLimit is not None:
            lp.solverModel.setOptionValue("time_limit", float(self.timeLimit))

        # set remaining parameter values
        for key, value in self.optionsDict.items():
            lp.solverModel.setOptionValue(key, value)

I have bolded the part we have modified. It looks like it works now.

**Comment by jajhall** [comment]
This is a bit of indiscipline on my part. I deleted `setLogCallback`, thinking it wasn't used - and because we were about to introduce more general callbacks - and then I put it back, at the request of a client! 

We should have a new Python version soon - maybe by Monday

**Comment by pchtsp** [comment]
users are still reporting this issue in pulp with the current released version in pypi. https://github.com/coin-or/pulp/issues/684#issuecomment-2012492370

Is this fixed in the released version? Thanks

**Comment by pchtsp** [comment]
or would you know a way to provide logs without using this functionality?

**Comment by jajhall** [comment]
The current [pypi](https://pypi.org/project/highspy/) version of HiGHS is still the rogue v1.5.3 in which `setLogCallback` was deleted from `highspy`.

However, [v1.7.1.dev1](https://pypi.org/project/highspy/#history) is now available. This allows the new [general callback mechanism](https://ergo-code.github.io/HiGHS/stable/callbacks/) to be used.

**Comment by jajhall** [comment]
> or would you know a way to provide logs without using this functionality?

See https://ergo-code.github.io/HiGHS/dev/interfaces/python/#Logging

**Comment by Cristian-Mattace** [comment]
Hi,
in highspy v1.7.1.dev1 I still have the same issue.

`File "/model/env/lib/python3.12/site-packages/pulp/apis/highs_api.py", line 481, in actualSolve
    self.createAndConfigureSolver(lp)
  File "/model/env/lib/python3.12/site-packages/pulp/apis/highs_api.py", line 329, in createAndConfigureSolver
    lp.solverModel.setLogCallback(*callbackTuple)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Highs' object has no attribute 'setLogCallback'. Did you mean: 'setCallback'?`

There is a solution for this?

**Comment by jajhall** [comment]
Thanks, I'll take a look at this

**Comment by JosephMPedersen** [comment]
I'm using pulp 2.8.0 with highspy 1.7.2, and getting the same error:

    AttributeError: 'Highs' object has no attribute 'setLogCallback'

I installed `highspy 1.7.2` via pip, which used `highspy-1.7.2-cp310-cp310-win_amd64.whl`

The full traceback is:

    ---------------------------------------------------------------------------
      AttributeError                            Traceback (most recent call last)
      Cell In[14], line 4
            1 # attempt to solve the lp, and check the status
            3 start_time2 = time()
      ----> 4 status = lp.solve(solver)
            5 stop_time2 = time()
            6 print(pulp.LpStatus[status])
    
      
      File [~\AppData\Local\anaconda3\envs\joe_env\lib\site-packages\pulp\pulp.py:1883](http://localhost:8888/lab/tree/ipynb/dasd_fr_py/~/AppData/Local/anaconda3/envs/joe_env/lib/site-packages/pulp/pulp.py#line=1882), in LpProblem.solve(self, solver, **kwargs)
         1881 # time it
         1882 self.startClock()
      -> 1883 status = solver.actualSolve(self, **kwargs)
         1884 self.stopClock()
         1885 self.restoreObjective(wasNone, dummyVar)
    
      
      File [~\AppData\Local\anaconda3\envs\joe_env\lib\site-packages\pulp\apis\highs_api.py:481](http://localhost:8888/lab/tree/ipynb/dasd_fr_py/~/AppData/Local/anaconda3/envs/joe_env/lib/site-packages/pulp/apis/highs_api.py#line=480), in HiGHS.actualSolve(self, lp)
          480 def actualSolve(self, lp):
      --> 481     self.createAndConfigureSolver(lp)
          482     self.buildSolverModel(lp)
          483     self.callSolver(lp)
    
      
      File [~\AppData\Local\anaconda3\envs\joe_env\lib\site-packages\pulp\apis\highs_api.py:329](http://localhost:8888/lab/tree/ipynb/dasd_fr_py/~/AppData/Local/anaconda3/envs/joe_env/lib/site-packages/pulp/apis/highs_api.py#line=328), in HiGHS.createAndConfigureSolver(self, lp)
          324 if self.msg or self.callbackTuple:
          325     callbackTuple = self.callbackTuple or (
          326         HiGHS.DEFAULT_CALLBACK,
          327         HiGHS.DEFAULT_CALLBACK_VALUE,
          328     )
      --> 329     lp.solverModel.setLogCallback(*callbackTuple)
          331 if self.gapRel is not None:
          332     lp.solverModel.setOptionValue("mip_rel_gap", self.gapRel)
    
      
      AttributeError: 'Highs' object has no attribute 'setLogCallback'

**Comment by jajhall** [comment]
`setLogCallback` has been replace by the logging callback mechanism set out in

https://ergo-code.github.io/HiGHS/stable/callbacks/

**Comment by jajhall** [comment]
Reopened the issue, but the HiGHS team is in no position to address it without a contribution from the PuLP community, as we are not PuLP users or Python programmers

**Comment by pchtsp** [comment]
Hello, I'm the maintainer of pulp, can I get a reproducible example so I
can identify the issue?

We run CI tests with HIGHS and they haven't failed recently.

**Comment by wakabame** [comment]
The issue appears to be resolved by upgrading to `pulp@2.9.0`. Testing different combinations of pulp and highspy versions with a simple linear programming example produced the following results:

### Script Used for Testing

```py
import pulp, highspy
pulp.__version__
import importlib.metadata
importlib.metadata.version("highspy")
model = pulp.LpProblem("Example", pulp.LpMinimize)
_var = pulp.LpVariable('a')
_var2 = pulp.LpVariable('a2')
model += _var + _var2 == 1
solver = pulp.HiGHS()
result = model.solve(solver)
```

### Test Results

#### `pulp@2.8.0` + `highspy@1.7.2` => fails

The following error occurred:

```python
AttributeError: 'Highs' object has no attribute 'setLogCallback'. Did you mean: 'setCallback'?
```
This issue suggests that `pulp@2.8.0` is incompatible with `highspy@1.7.2` due to the setLogCallback method being unavailable.

<details>

```py
>>> import pulp, highspy
>>> pulp.__version__
'2.8.0'
>>> import importlib.metadata
>>> importlib.metadata.version("highspy")
'1.7.2'
>>> model = pulp.LpProblem("Example", pulp.LpMinimize)
>>> _var = pulp.LpVariable('a')
>>> _var2 = pulp.LpVariable('a2')
>>> model += _var + _var2 == 1
>>> solver = pulp.HiGHS()
>>> result = model.solve(solver)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
    lp.solverModel.setLogCallback(*callbackTuple)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Highs' object has no attribute 'setLogCallback'. Did you mean: 'setCallback'?
```

</details>

#### `pulp@2.9.0` + `highspy@1.7.1` => Succeeds
The solver successfully runs and returns an optimal solution.

<details>

```py
>>> import pulp, highspy
>>> pulp.__version__
'2.9.0'
>>> import importlib.metadata
>>> importlib.metadata.version("highspy")
'1.7.1'
>>> model = pulp.LpProblem("Example", pulp.LpMinimize)
>>> _var = pulp.LpVariable('a')
>>> _var2 = pulp.LpVariable('a2')
>>> model += _var + _var2 == 1
>>> solver = pulp.HiGHS()
>>> result = model.solve(solver)
Running HiGHS 1.7.1 (git hash: 0c240d8): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [1e+00, 1e+00]
  Cost   [1e+00, 1e+00]
  Bound  [0e+00, 0e+00]
  RHS    [1e+00, 1e+00]
Presolving model
0 rows, 0 cols, 0 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve : Reductions: rows 0(-1); columns 0(-3); elements 0(-2) - Reduced to empty
Solving the original LP from the solution after postsolve
Model   status      : Optimal
Objective value     :  0.0000000000e+00
HiGHS run time      :          0.00
```

</details>

#### `pulp@2.9.0` + `highspy@1.7.2` => Succeeds
The solver successfully runs and returns an optimal solution.

<details>

```py
>>> import pulp, highspy
>>> pulp.__version__
'2.9.0'
>>> import importlib.metadata
>>> importlib.metadata.version("highspy")
'1.7.2'
>>> model = pulp.LpProblem("Example", pl.LpMinimize)
>>> _var = pulp.LpVariable('a')
>>> _var2 = pulp.LpVariable('a2')
>>> model += _var + _var2 == 1
>>> solver = pulp.HiGHS()
>>> result = model.solve(solver)
Running HiGHS 1.7.2 (git hash: 184e327): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [1e+00, 1e+00]
  Cost   [1e+00, 1e+00]
  Bound  [0e+00, 0e+00]
  RHS    [1e+00, 1e+00]
Presolving model
0 rows, 0 cols, 0 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve : Reductions: rows 0(-1); columns 0(-3); elements 0(-2) - Reduced to empty
Solving the original LP from the solution after postsolve
Model   status      : Optimal
Objective value     :  0.0000000000e+00
HiGHS run time      :          0.00
```

</details>

### Conclusion

The issue with `pulp@2.8.0` and `highspy@1.7.2` is caused by the absence of the `setLogCallback` method.
Upgrading to `pulp@2.9.0` resolves the problem, with both `highspy@1.7.1` and `highspy@1.7.2` working correctly.
