### ISSUE TITLE
Problems with warm start solutions. It identifies them as infeasible

### ISSUE THREAD

**Issue by sgnieto** [ERGO-Code/HiGHS#2463]
I'm trying to solve a model with a warm solution because it's very huge, more than 600000 variables. I check that all the constraints defined in the model are passed in the warm solution before generate the file and used it to solve the model.

However, I'm getting infeasibilities that makes me set mip_feasibility_tolerance to 1, to get it work. 
Running HiGHS 1.11.0 (git hash: 364c83a51): Copyright (c) 2025 HiGHS under MIT licence terms
Set option presolve to "on"
Set option parallel to "on"
Set option primal_feasibility_tolerance to 0.001
Set option dual_feasibility_tolerance to 0.001
Set option simplex_scale_strategy to 1
Set option simplex_max_concurrency to 6
Set option log_file to "C:\Users\sgarcia\AppData\Local\Temp\highs-qS9j05\highs.log"
Set option write_solution_to_file to true
Set option read_solution_file to "C:\sgn\wspc\pocTsCompras\warm-start.sol"
Set option solution_file to "C:\Users\sgarcia\AppData\Local\Temp\highs-qS9j05\solution.txt"
Set option mip_max_start_nodes to 100
Set option mip_feasibility_tolerance to 0.0001
MIP  model has 12875 rows; 625028 cols; 5920991 nonzeros; 612154 integer variables (612154 binary)
Coefficient ranges:
  Matrix [2e-02, 1e+06]
  Cost   [1e+00, 1e+04]
  Bound  [1e-03, 2e+08]
  RHS    [1e+00, 1e+00]
Assessing feasibility of MIP using primal feasibility and integrality tolerance of      0.0001
WARNING: Col 625026 has         infeasibility of       0.001 from [lower, value, upper] = [          0.001;               0;   2.0367255e+08]
WARNING: Row   6434 has         infeasibility of           1 from [lower, value, upper] = [              1;               0;             inf]
Solution has               num          max          sum
Col     infeasibilities      1        0.001        0.001
Integer infeasibilities      0            0            0
Row     infeasibilities      1            1            1
Row     residuals            0            0            0
Attempting to find feasible solution by solving LP for user-supplied values of discrete variables

Playing with tolerances I'm able to continue, but highs set objective to 0.

Running HiGHS 1.11.0 (git hash: 364c83a51): Copyright (c) 2025 HiGHS under MIT licence terms
Set option presolve to "on"
Set option parallel to "on"
Set option primal_feasibility_tolerance to 0.001
Set option dual_feasibility_tolerance to 1
Set option simplex_scale_strategy to 1
Set option simplex_max_concurrency to 6
Set option log_file to "C:\Users\sgarcia\AppData\Local\Temp\highs-qS9j05\highs.log"
Set option write_solution_to_file to true
Set option read_solution_file to "C:\sgn\wspc\pocTsCompras\warm-start.sol"
Set option solution_file to "C:\Users\sgarcia\AppData\Local\Temp\highs-qS9j05\solution.txt"
Set option mip_max_start_nodes to 100
Set option mip_feasibility_tolerance to 1
MIP  model has 12875 rows; 625028 cols; 5920991 nonzeros; 612154 integer variables (612154 binary)
Coefficient ranges:
  Matrix [2e-02, 1e+06]
  Cost   [1e+00, 1e+04]
  Bound  [1e-03, 2e+08]
  RHS    [1e+00, 1e+00]
Assessing feasibility of MIP using primal feasibility and integrality tolerance of           1
Solution has               num          max          sum
Col     infeasibilities      0            0            0
Integer infeasibilities      0            0            0
Row     infeasibilities      0            0            0
Row     residuals            0            0            0
Presolving model
10965 rows, 623119 cols, 4686433 nonzeros  15s
4984 rows, 464609 cols, 2666057 nonzeros  57s
4984 rows, 463212 cols, 2658834 nonzeros  69s

MIP start solution is feasible, objective value is 0

Solving MIP model with:
   4984 rows
   463212 cols (0 binary, 458228 integer, 0 implied int., 4984 continuous, 0 domain fixed)
   2658834 nonzeros

I'm sure that the model is feasible, because if I eliminate 200000 variables of the set I'm testing the objective is feasible, the model is feasible from the begining but with some noise.

I've attached model, opts and warm start, so you can test it.

[highs.opt.txt](https://github.com/user-attachments/files/21180129/highs.opt.txt)
[warm-start.sol.txt](https://github.com/user-attachments/files/21180128/warm-start.sol.txt)

[model.part05.rar.txt](https://github.com/user-attachments/files/21180184/model.part05.rar.txt)
[model.part01.rar.txt](https://github.com/user-attachments/files/21180185/model.part01.rar.txt)

[model.part04.rar.txt](https://github.com/user-attachments/files/21180209/model.part04.rar.txt)
[model.part03.rar.txt](https://github.com/user-attachments/files/21180208/model.part03.rar.txt)
[model.part02.rar.txt](https://github.com/user-attachments/files/21180207/model.part02.rar.txt)

**Comment by jajhall** [comment]
The problem is that in using a `.lp` file to store your model, when HiGHS loads the file the order of the variables is not the same as the order of the variables in the `.sol` file.

This is because the order of the variables after reading a `.lp` file is determined by the order in which they are first seen in the file. In particular, if variables don't appear in the objective function, they will be ordered after all the variables that do.

Hence some variables are not being set to the value next to their name in the `.sol` file. 

Specifically, I see that in the `.sol` file you have

pt_nuevo 161816004.74149838

This is variable 612154 in the  `.sol` file but, after reading in the `.lp` file, pt_nuevo is variable 625026. Hence it's set to the value of variable 625026 in the  `.sol` file

slack_plazo_medio_ponderado_pil_b 0

leading to the value of 0 for pt_nuevo not being feasible with respect to its bounds of  [0.001, 2.03673e+08]

Sorry, this is opaque behaviour, and it's reasonable to expect HiGHS to match names in the model to names in the solution file.

I'll work on the fix now

**Comment by sgnieto** [comment]
Thanks a lot.

**Comment by jajhall** [comment]
I've not merged the fix, and this will be merged to "latest" anyway, as master is only for releases. 

You'll have something to try later today

**Comment by jajhall** [comment]
HiGHS (https://github.com/ERGO-Code/HiGHS/tree/fix-2463) now reads your solution file correctly, but only after I changed 

> \# Columns undefined

to

> \# Columns 625028

I guess you wrote the solution file yourself, as I don't see how HiGHS would have written "undefined" rather than the number of columns of the LP for which the solution file was written.

Once HiGHS has solved the LP corresponding to the integer variables being fixed at the values you gave, it uses the solution to get an initial primal bound in the MIP solver

Unfortunately, the MIP solver takes a _very_ long time in presolve, so I recommend that you run with `presolve=off`

The following settings in your options file are unwise or ineffective

> parallel=on
simplex_scale_strategy=1
simplex_max_concurrency=6
primal_feasibility_tolerance=0.0001
dual_feasibility_tolerance=0.0001
mip_feasibility_tolerance=0.0001

I'm curious to know why you set
> mip_max_start_nodes=100

There's quite a lot of work to be approved in #2465 so I suggest that you checkout [fix-2463](https://github.com/ERGO-Code/HiGHS/tree/fix-2463).

**Comment by sgnieto** [comment]
If I use this format:
=obj=203672547.1
sel_0 0
sel_1 0
sel_2 0
sel_3 0
sel_4 0
sel_5 0
sel_6 0
sel_7 0
sel_8 1
sel_9 0
sel_10 0
sel_11 0
sel_12 0
sel_13 0
sel_14 0
sel_15 1
sel_16 0
sel_17 0
sel_18 0
sel_19 0
sel_20 1
sel_21 1
sel_22 0
sel_23 0
sel_24 0
sel_25 0
sel_26 0
sel_27 0
sel_28 0
sel_29 0
sel_30 0
sel_31 1
sel_32 0
sel_33 0
sel_34 0
sel_35 0
sel_36 0
sel_37 0
sel_38 0
sel_39 0
sel_40 0
sel_41 0
sel_42 0
sel_43 0
sel_44 0
sel_45 0
sel_46 0
sel_47 0
...
slackVariablesRestricted 0

I'm still having an infeasible row.

**Comment by jajhall** [comment]
Does [fix-2463](https://github.com/ERGO-Code/HiGHS/tree/fix-2463) work now?

If not, please send me the model and solution file that yield an infeasible row

**Comment by sgnieto** [comment]
After testing with the fix I'm still having the issue, please find attached the model and warm solution.
[highs-jGQrmY.part01.rar.txt](https://github.com/user-attachments/files/21315828/highs-jGQrmY.part01.rar.txt)
[highs-jGQrmY.part02.rar.txt](https://github.com/user-attachments/files/21315829/highs-jGQrmY.part02.rar.txt)
[highs-jGQrmY.part03.rar.txt](https://github.com/user-attachments/files/21315826/highs-jGQrmY.part03.rar.txt)
[highs-jGQrmY.part04.rar.txt](https://github.com/user-attachments/files/21315830/highs-jGQrmY.part04.rar.txt)
[highs-jGQrmY.part05.rar.txt](https://github.com/user-attachments/files/21315827/highs-jGQrmY.part05.rar.txt)

**Comment by jajhall** [comment]
> If I use this format:
> =obj=203672547.1

HiGHS gives an error message, although it's only thrown when it reaches line

> sel_5 0

The MIPLIB solution file needs a space after the keyword 

> =obj= 203672547.1
