### ISSUE TITLE
Bugs in MIP solver

### ISSUE THREAD

**Issue by odow** [ERGO-Code/HiGHS#522]
I'm trying to wrap the MIP solver in JuMP and running into some problems (https://github.com/jump-dev/HiGHS.jl/pull/53).

Here's one. The problem is:
```
variables: x
minobjective: -2.0x
c1: x <= 1.5
c2: x in Integer()
```
which I wrote as
```Julia
julia> colvalue, rowvalue, modelstatus = [NaN], Float64[], Ref{Cint}()
([NaN], Float64[], Base.RefValue{Int32}(1017652688))

julia> Highs_mipCall(
           Cint(1), Cint(0), Cint(0),       # numcol, numrow, numnz    
           Cint(0),                         # rowwise
           Cint(1),                         # sense (minimize)
           0.0, [-2.0],                     # offset, colcost
           [-Inf], [1.5],                   # collower, colupper
           Cint[], Cint[],                  # rowlower, rowupper
           Cint[0], Cint[], Cdouble[],      # astart, aindex, avalue
           Cint[1],                         # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 1.5

julia> rowvalue
Float64[]

julia> modelstatus
Base.RefValue{Int32}(7)
```
It seems that the integrality flag (1 = integer) doesn't work because it returns a fractional solution.

Or do I need to set different settings for the MIP solver?

If I add a constraint `-2 <= x <= 2`, then it reports `kInfeasible`.
```Julia
julia> colvalue, rowvalue, modelstatus = [NaN], Float64[], Ref{Cint}()
([NaN], Float64[], Base.RefValue{Int32}(1115897232))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(0),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 NaN

julia> rowvalue
Float64[]

julia> modelstatus
Base.RefValue{Int32}(8)
```

And then there's this weird non-deterministic behavior, where as I repeatedly flip the rowwise bit (which AFAIK, should do nothing because the matrix is 1x1), then it oscillates between reporting infeasible and optimal with the solution `x=0` (not the `x=1` optimal solution).
```Julia
julia> colvalue, rowvalue, modelstatus = [NaN], [NaN], Ref{Cint}()
([NaN], [NaN], Base.RefValue{Int32}(1117170640))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(0),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 NaN

julia> rowvalue
1-element Vector{Float64}:
 NaN

julia> modelstatus
Base.RefValue{Int32}(8)

julia> colvalue, rowvalue, modelstatus = [NaN], [NaN], Ref{Cint}()
([NaN], [NaN], Base.RefValue{Int32}(1117278928))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(1),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 NaN

julia> rowvalue
1-element Vector{Float64}:
 NaN

julia> modelstatus
Base.RefValue{Int32}(8)

julia> colvalue, rowvalue, modelstatus = [NaN], [NaN], Ref{Cint}()
([NaN], [NaN], Base.RefValue{Int32}(1117471280))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(0),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 2.121995791e-314

julia> rowvalue
1-element Vector{Float64}:
 2.121995791e-314

julia> modelstatus
Base.RefValue{Int32}(7)

julia> colvalue, rowvalue, modelstatus = [NaN], [NaN], Ref{Cint}()
([NaN], [NaN], Base.RefValue{Int32}(154230672))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(1),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 6.95367410720365e-310

julia> rowvalue
1-element Vector{Float64}:
 6.95367410720365e-310

julia> modelstatus
Base.RefValue{Int32}(7)

julia> colvalue, rowvalue, modelstatus = [NaN], [NaN], Ref{Cint}()
([NaN], [NaN], Base.RefValue{Int32}(1117737328))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(0),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 1.39069238152491e-309

julia> rowvalue
1-element Vector{Float64}:
 1.39069238152491e-309

julia> modelstatus
Base.RefValue{Int32}(7)

julia> colvalue, rowvalue, modelstatus = [NaN], [NaN], Ref{Cint}()
([NaN], [NaN], Base.RefValue{Int32}(1118065072))

julia> Highs_mipCall(
           Cint(1), Cint(1), Cint(1),          # numcol, numrow, numnz    
           Cint(1),                            # rowwise
           Cint(1),                            # sense (minimize)
           0.0, [-2.0],                        # offset, colcost
           [-Inf], [1.5],                      # collower, colupper
           Cint[-2.0], Cint[2.0],              # rowlower, rowupper
           Cint[0, 1], Cint[0], Cdouble[1.0],  # astart, aindex, avalue
           Cint[1],                            # integrality
           colvalue, rowvalue, modelstatus,
       )
0

julia> colvalue
1-element Vector{Float64}:
 NaN

julia> rowvalue
1-element Vector{Float64}:
 NaN

julia> modelstatus
Base.RefValue{Int32}(8)
```

Thoughts @galabovaa?

**Comment by jajhall** [comment]
@galabovaa Which branch of HiGHS is currently being used for the Julia interface? 

Highs/master doesn't (yet) have sense or offset in the parameter list for Highs_mipCall in the C interface.

**Comment by galabovaa** [comment]
We have made sure that the HiGHS_jll builds OK with the new solvers, so I merged the changes into HiGHS master and opened a PR to build the jll with the corresponding HiGHS master commit # 40fa96a10554d76b1413bf33cc79a2153aa1db13

@jajhall I see that master now has the sense and offset in the parameter list, I suppose maybe @lgottwald added it in the mean time

**Comment by jajhall** [comment]
I put these into the parameter list, and it's now that they migrated into master. 

NB @odow the interpretation of the rowwise parameter in Highs_mipCall will change in V1.0.0. Currently it corresponds to a bool, but we will probably need a more general format in future. So, in the branch I'm working on (and in V1.0.0) 0 will mean "No format", 1 "Columnwise" and 2 "Rowwise"

**Comment by odow** [comment]
Okay, I'll try again with the latest JLL build. 

> the interpretation of the rowwise parameter in Highs_mipCall will change in V1.0.0

No problem.

**Comment by odow** [comment]
I'll also say: the MIP solver passes all the larger unit tests and actual problems.

It just fails some of the more niche unit tests like the one above when there are no constraints.

**Comment by odow** [comment]
Just to follow up, I can still reproduce this on the most recent commit to master: https://github.com/ERGO-Code/HiGHS/commit/40fa96a10554d76b1413bf33cc79a2153aa1db13

**Comment by jajhall** [comment]
I've reproduced the first bug.
@lgottwald I've set this up as unit test MIP-od in mip-conflict-analysis

**Comment by lgottwald** [comment]
This should be fixed
